name: Gather observing

on:
  schedule:
    - cron: '*/30 1-13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install xvfb
        python -m pip install --upgrade pip
        pip install get-chrome-driver --upgrade
        pip install -r requirements.txt
    - name: Observe gather space
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 120
        max_attempts: 3
        retry_on: error
        command: python main.py ${{secrets.GATHER_SPACE_URL}} ${{secrets.GATHER_SPACE_PASSWORD}} ${{secrets.DISCORD_API_SECRET}} ${{secrets.DISCORD_CHANNEL_ID}} --name ${{secrets.OBSERVER_USER_NAME}} 
    - name: Save failure screenshot
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: screenshot
        path: ./screenshot.png
